server:
  port: 8188
  servlet:
    context-path: /ff-personal
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:findfoodDB;MODE=PostgreSQL
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: none
        temp:
            use_jdbc_metadata_defaults: false
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

integrations:
  menu-service:
    url: http://localhost:8187/ff-menu
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000



